global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'goapi'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:3000']  # For local development

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']